version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB='your db name'
      - POSTGRES_USER='your db user name'
      - POSTGRES_PASSWORD='password'
      
  backend-service-dev:
    restart: always
    build: eng_gls_backend/
    entrypoint: /app/back-end/entrypoint_dev.sh
    volumes:
      - ./eng_gls_backend:/app/back-end
    ports:
      - 8000:8000
    depends_on:
      - db
         
  frontend-service-dev:
    restart: always
    build:
        context: eng_gls_frontend
        dockerfile: dev.Dockerfile
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./eng_gls_frontend:/app/front-end
    ports:
      - 3000:3000
