# Generated by Django 3.2.8 on 2021-10-15 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glossary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordInGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeated', models.IntegerField()),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary_app.glossary')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary_app.word')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_text', models.TextField()),
                ('description', models.TextField()),
                ('for_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary_app.word')),
                ('translation_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
